server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  thymeleaf:
#    prefix:
#      classpath: templates/
#    suffix: .html
#    mode: HTML5

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6537b83f0a511fe480aa2935332bdc93
            client-secret: shHhhIDjXx7BJHiwbtnaCt1hM5JQiYk6
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

          naver:
            client-id: vSiH6o_RwIudwARHyO8k
            client-secret: NHaiXXMCgD
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

logging:
  level:
    '[com.example.kakao]': DEBUG
    '[org.hibernate.type]': TRACE


file:
  path: ./img/

